### ISSUE TITLE
[epic] Centralize Kubernetes component building into rancher/image-build-kubernetes and drop kube-proxy helm chart

### ISSUE THREAD

**Issue by brandond** [rancher/rke2#1190]
This is a high-level tracking issue for work to refactor how we build and deploy Kubernetes components.

### Goals
* Move Kubernetes component building out of rancher/rke2:
    * #1078
    * #1104
* Switch kube-proxy over to a static pod managed by the supervisor/agent instead of Daemonset: 
    * #751

### Scope
The current plan is to backport these changes to **all active branches**.

### Tasks
1. [x] Bring https://github.com/rancher/image-build-kubernetes back to life and up-to-date with the current build scripts, mostly cribbed from image-build-kube-proxy; ensure that it also builds the kube-proxy binary.
    History: we stopped using it when we decided to build most of the Kubernetes stuff in RKE2, and kube-proxy in the image-build-kube-proxy repo.
2. [x] Pull all the Kubernetes build stuff out of the RKE2 dockerfile, replace it with FROM hardened-kubernetes from image-build-kubernetes
    * #1191
    * #1192
    * #1193
    * #1194
3. [x] Implement the missing bits of the kube-proxy static pod executor in RKE2 - have it use the same hardened-kubernetes image as the rest of the control plane, plumb through the options, restore the disabled CLI flag, etc.
    * #1195
    * #1196
    * #1197
    * #1198
4. [x] Disable the rke2-kube-proxy helm chart from rke2-charts; stop hardcoding `--disable-kube-proxy` and use the static pod executor to launch it.
    **TODO:*** Figure out how to handle this from an upgrade perspective - may want to keep `--disable-kube-proxy` set and not disable the rke2-kube-proxy helm chart if we detect a rke2-kube-proxy HelmChartConfig resource present in the cluster, similar to what we did for the K3s traefik upgrade?
    * #1199
    * #1200
    * #1201
    * #1202

**Comment by brandond** [comment]
All the work for this has landed on master and release branches. Closing.
