### ISSUE TITLE
[epic] Kubernetes 1.23 Charts Validation and Image Updates

### ISSUE THREAD

**Issue by cwayne18** [rancher/rke2#2079]
We need to validate that all feature charts work with Kubernetes 1.22. We also need to ensure that all the images, both core and for packaged components, are updated. This issue is to track that work.

Related issues:
* https://github.com/rancher/rke2/issues/1026
* https://github.com/rancher/rke2/issues/1714
* https://github.com/rancher/rke2/issues/1839

### RKE2 Core
* [ ] Update core Images:
  https://github.com/rancher/rke2/pull/1827
  * [ ] rancher/hardened-kubernetes [rancher/image-build-kubernetes](https://github.com/rancher/image-build-kubernetes)
    https://github.com/rancher/image-build-kubernetes/pull/16
  * [ ] rancher/hardened-containerd [rancher/image-build-containerd](https://github.com/rancher/image-build-containerd)
    https://github.com/rancher/image-build-containerd/pull/11
  * [ ] rancher/hardened-crictl [rancher/image-build-crictl](https://github.com/rancher/image-build-crictl)
      https://github.com/rancher/image-build-crictl/pull/4
  * [ ] rancher/hardened-runc [rancher/image-build-runc](https://github.com/rancher/image-build-runc)
      https://github.com/rancher/image-build-runc/pull/7
  * [ ] rancher/rke2-cloud-provider [rancher/image-build-rke2-cloud-provider](https://github.com/rancher/image-build-rke2-cloud-provider)
      https://github.com/rancher/image-build-rke2-cloud-provider/pull/7
  * [ ] rancher/hardened-etcd [rancher/image-build-etcd](https://github.com/rancher/image-build-etcd)
    https://github.com/rancher/image-build-etcd/pull/5
  * [ ] docker.io/rancher/klipper-helm [k3s-io/klipper-helm](https://github.com/k3s-io/klipper-helm)
    no update needed; the embedded helm supports 1.22

### rke2-canal
* [ ] Confirm canal works on 1.22
* [ ] Update helm chart
    https://github.com/rancher/rke2-charts/pull/151
    https://github.com/rancher/rke2-charts/pull/160
    https://github.com/rancher/rke2-charts/pull/161
* [ ] Update canal images:
  * [ ] rancher/hardened-cni-plugins [rancher/image-build-cni-plugins](https://github.com/rancher/image-build-cni-plugins)
  https://github.com/rancher/image-build-cni-plugins/pull/1
  * [ ] rancher/hardened-calico [rancher/image-build-calico](https://github.com/rancher/image-build-calico)
  https://github.com/rancher/image-build-calico/pull/7
  * [ ] rancher/hardened-flannel [rancher/image-build-flannel](https://github.com/rancher/image-build-flannel)
  https://github.com/rancher/image-build-flannel/pull/11
  https://github.com/rancher/image-build-flannel/pull/12

### rke2-coredns
* [ ] Confirm CoreDNS and all features work on 1.22
* [ ] Update helm chart
  https://github.com/rancher/rke2-charts/pull/158
* [ ] Update CoreDNS images:
  * [ ] rancher/hardened-cluster-autoscaler [rancher/image-build-coredns](https://github.com/rancher/image-build-coredns)
  https://github.com/rancher/image-build-coredns/pull/8
  https://github.com/rancher/image-build-coredns/pull/9
  * [ ] rancher/hardened-coredns [rancher/image-build-coredns](https://github.com/rancher/image-build-coredns)
  https://github.com/rancher/image-build-coredns/pull/8
  https://github.com/rancher/image-build-coredns/pull/9
  * [ ] rancher/hardened-dns-node-cache [rancher/image-build-dns-nodecache](https://github.com/rancher/image-build-dns-nodecache)
  https://github.com/rancher/image-build-dns-nodecache/pull/3

### rke2-metrics-server
* [ ]  Confirm metrics-server works on 1.22
* [ ] Update helm chart
    https://github.com/rancher/rke2-charts/pull/153
* [ ] Update metrics-server images:
  * [ ] rancher/hardened-k8s-metrics-server [rancher/image-build-k8s-metrics-server](https://github.com/rancher/image-build-k8s-metrics-server)
  https://github.com/rancher/rke2-charts/pull/153

### rke2-ingress-nginx
* [ ] Confirm ingress-nginx works on 1.22
* [ ] Update helm chart
  https://github.com/rancher/rke2-charts/pull/156
* [ ] Update ingress-nginx image:
  * [ ] rancher/nginx-ingress-controller [rancher/ingress-nginx](https://github.com/rancher/ingress-nginx)
  https://github.com/rancher/ingress-nginx/pull/61
  https://github.com/rancher/ingress-nginx/pull/62
  https://github.com/rancher/ingress-nginx/pull/63
  https://github.com/rancher/ingress-nginx/pull/64
  https://github.com/rancher/ingress-nginx/pull/65
  https://github.com/rancher/ingress-nginx/pull/66
  * [x] rancher/mirrored-jettech-kube-webhook-certgen (update to rancher/mirrored-ingress-nginx-kube-webhook-certgen)
  https://github.com/rancher/image-mirror/pull/167
  https://github.com/rancherlabs/eio/issues/594

### rke2-calico
* [ ] Confirm calico works on 1.22
* [ ] Update helm chart
    https://github.com/rancher/rke2-charts/pull/154
* [ ] Update mirrored calico images: [rancher/image-mirror](https://github.com/rancher/image-mirror)
    ```
    rancher/mirrored-calico-operator
    rancher/mirrored-calico-ctl
    rancher/mirrored-calico-kube-controllers
    rancher/mirrored-calico-typha
    rancher/mirrored-calico-node
    rancher/mirrored-calico-pod2daemon-flexvol
    rancher/mirrored-calico-cni
    rancher/mirrored-calico-apiserver
    ```
    https://github.com/rancherlabs/eio/issues/597
    https://github.com/rancher/image-mirror/pull/169

### rke2-cilium
* [ ] Confirm cilium works on 1.22
* [ ] Update helm chart
  https://github.com/rancher/rke2-charts/pull/143
  https://github.com/rancher/rke2-charts/pull/146
  https://github.com/rancher/rke2-charts/pull/159
  https://github.com/rancher/rke2-charts/pull/164
* [ ] Update mirrored cilium images: [rancher/image-mirror](https://github.com/rancher/image-mirror)
  https://github.com/rancher/image-mirror/pull/159
    ```
    rancher/mirrored-cilium-cilium
    rancher/mirrored-cilium-operator-aws
    rancher/mirrored-cilium-operator-azure
    rancher/mirrored-cilium-operator-generic
    rancher/mirrored-cilium-startup-script
    ```

### rke2-multus
* [ ] Confirm multus works on 1.22
* [ ] Update helm chart
  https://github.com/rancher/rke2-charts/pull/163
* [ ] Update images:
  * [ ] rancher/hardened-multus-cni [rancher/image-build-multus](https://github.com/rancher/image-build-multus)
  https://github.com/rancher/image-build-multus/pull/9
  https://github.com/rancher/image-build-multus/pull/10
  * [ ] rancher/hardened-sriov-cni [rancher/image-build-sriov-cni](https://github.com/rancher/image-build-sriov-cni)
  https://github.com/rancher/image-build-sriov-cni/pull/3
    
### rancher-sriov
* [ ] Confirm sriov works on 1.22
* [ ] Update helm chart [in rancher/charts](https://github.com/rancher/charts/tree/dev-v2.6/charts/rancher-sriov)
https://github.com/rancher/charts/pull/1540
* [ ] Update images
  * [ ] rancher/hardened-ib-sriov-cni [rancher/image-build-ib-sriov-cni](https://github.com/rancher/image-build-ib-sriov-cni)
  https://github.com/rancher/image-build-ib-sriov-cni/pull/3
  * [ ] rancher/hardened-cni-plugins [rancher/image-build-cni-plugins](https://github.com/rancher/image-build-cni-plugins)
  https://github.com/rancher/image-build-cni-plugins/pull/1
  * [ ] rancher/hardened-sriov-network-config-daemon [rancher/image-build-sriov-operator](https://github.com/rancher/image-build-sriov-operator)
  https://github.com/rancher/image-build-sriov-operator/pull/10
  * [ ] rancher/hardened-sriov-network-operator [rancher/image-build-sriov-operator](https://github.com/rancher/image-build-sriov-operator)
  https://github.com/rancher/image-build-sriov-operator/pull/10
  * [ ] rancher/hardened-sriov-network-webhook [rancher/image-build-sriov-operator](https://github.com/rancher/image-build-sriov-operator)
  https://github.com/rancher/image-build-sriov-operator/pull/10
  * [ ] rancher/hardened-sriov-network-device-plugin [rancher/image-build-sriov-network-device-plugin](https://github.com/rancher/image-build-sriov-network-device-plugin)
  https://github.com/rancher/image-build-sriov-network-device-plugin/pull/5
  * [ ] rancher/hardened-sriov-network-resources-injector [rancher/image-build-sriov-network-resources-injector](https://github.com/rancher/image-build-sriov-network-resources-injector)
  https://github.com/rancher/image-build-sriov-network-resources-injector/pull/5

### rancher-vsphere-cpi and rancher-vsphere-csi
* [ ] Confirm vsphere works on 1.22
* [ ] Update helm chart
* [ ] Update mirrored vsphere images: [rancher/image-mirror](https://github.com/rancher/image-mirror)
    ```
    rancher/mirrored-cloud-provider-vsphere-cpi-release-manager
    rancher/mirrored-cloud-provider-vsphere-csi-release-driver
    rancher/mirrored-cloud-provider-vsphere-csi-release-syncer
    rancher/mirrored-k8scsi-csi-attacher
    rancher/mirrored-k8scsi-csi-node-driver-registrar
    rancher/mirrored-k8scsi-csi-provisioner
    rancher/mirrored-k8scsi-csi-resizer
    rancher/mirrored-k8scsi-livenessprobe
    ```
    
### rancher-vsphere-cpi and rancher-vsphere-csi
* [ ] Confirm harvester works on 1.22
* [ ] Update helm chart

**Comment by katran001** [comment]
we can close this out; the initial release of 1.23 is complete.
