### ISSUE TITLE
Release v1.18.9+rke2

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rke2#408]
**Summary:**
Task covering release work. 

**List of required releases:**
_To release as soon as able:_
N/A (no additional rcs / betas are needed for QA)

_To release once have approval from QA:_
v1.18.9+rke2

**Prep work:**
- [x] EIO team notified of the incoming releases (drone impact)
- [x] PM Draft Releases (fill in release notes, mark as pre-release, fill in title, set target release branch, leave tag version blank, save as draft)

**Release work:**
- [x] Tag and release v1.18.9+rke2

**Post-Release work:**
- [x] Uncheck "Pre-release" once drone is complete and all release artifacts are there
- [x] Merge in channel server change https://github.com/rancher/rke2/issues/403
- [x] (Rancher PM) Merge in rancher/kontainter-driver-metadata change, and QA test this https://github.com/rancher/rke2/issues/383
- [ ] Create stable channel. When we are ready, promote the release to stable https://github.com/rancher/rke2/issues/404

**Comment by davidnuzik** [comment]
Moved to working since we're working on release notes and otherwise prepping.

**Comment by davidnuzik** [comment]
We will manage the stable channel part of this via https://github.com/rancher/rke2/issues/404 and I'm going to close this out. The release is out!! :)

**Comment by ShylajaDevadiga** [comment]
Validated without specifying channel latest works.
On Ubuntu 20.04, RHEL 7.8, RHEL 8.2
