### ISSUE TITLE
[Epic] RKE2 Testing Overhaul 2024

### ISSUE THREAD

**Issue by dereknola** [rancher/rke2#5678]
This is an epic to track all the changes for testing in H1 2024. Since most testing is self tested in the CI, QA for most of this is not necessary.

### Unit tests
- [x] https://github.com/rancher/rke2/issues/5677
- Add more unit test coverage, open issues as necessary
- [x] https://github.com/rancher/rke2/issues/6143

### Integration
- [x] Standardize integration testing (with https://github.com/rancher/rke2/pull/5679)
- [x] https://github.com/rancher/rke2/issues/5386
- [x] Run Integration testing on PRs using GitHub Actions (with https://github.com/rancher/rke2/pull/5679)
- [x] Enable Go coverage for integration tests, upload to codecov (with https://github.com/rancher/rke2/pull/5679)

### Install
- [x] https://github.com/rancher/rke2/issues/5691

### E2E
- [x] https://github.com/rancher/rke2/issues/5863
- [x]  https://github.com/rancher/rke2/issues/6023
- [x] https://github.com/rancher/rke2/issues/6119

### Docker 
- Move docker tests out of "scripts" folder
